%%Step 1a

                %% Import data from text file.
                % Script for importing data from the following text file:
                %
                %    /Users/tgallen/Dropbox/Numerical Methods/Lecture 17 - Likelihoods and
                %    Filtering/data.csv
                %
                % To extend the code to different selected data or a different text file,
                % generate a function instead of a script.

                % Auto-generated by MATLAB on 2015/10/09 08:47:17

                %% Initialize variables.
                filename = '/Users/tgallen/Dropbox/Numerical Methods/Lecture 17 - Likelihoods and Filtering/data.csv';
                delimiter = ',';
                startRow = 2;

                %% Format string for each line of text:
                %   column1: double (%f)
                %	column2: double (%f)
                %   column3: double (%f)
                %	column4: double (%f)
                %   column5: double (%f)
                %	column6: double (%f)
                %   column7: double (%f)
                %	column8: double (%f)
                %   column9: double (%f)
                %	column10: double (%f)
                %   column11: double (%f)
                %	column12: double (%f)
                % For more information, see the TEXTSCAN documentation.
                formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

                %% Open the text file.
                fileID = fopen(filename,'r');

                %% Read columns of data according to format string.
                % This call is based on the structure of the file used to generate this
                % code. If an error occurs for a different file, try regenerating the code
                % from the Import Tool.
                dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

                %% Close the text file.
                fclose(fileID);

                %% Post processing for unimportable data.
                % No unimportable data rules were applied during the import, so no post
                % processing code is included. To generate code which works for
                % unimportable data, select unimportable cells in a file and regenerate the
                % script.

                %% Allocate imported array to column variable names
                ID = dataArray{:, 1};
                TIRE = dataArray{:, 2};
                TPOP = dataArray{:, 3};
                NGRW = dataArray{:, 4};
                PGRW = dataArray{:, 5};
                OCTY = dataArray{:, 6};
                OPOP = dataArray{:, 7};
                LANDV = dataArray{:, 8};
                ELD = dataArray{:, 9};
                FFRAC = dataArray{:, 10};
                PINC = dataArray{:, 11};
                LNHDD = dataArray{:, 12};


                %% Clear temporary variables
                clearvars filename delimiter startRow formatSpec fileID dataArray ans;

                id = ID;
                tire = TIRE;
                tpop = TPOP;
                ngrw = NGRW;
                pgrw = PGRW;
                octy = OCTY;
                opop = OPOP;
                landv = LANDV;
                eld = ELD;
                ffrac = FFRAC;
                pinc = PINC;
                lnhdd = LNHDD;
% load data.mat

g0 = 1e-2*ones(19,1); %initial guesses
%lower bound: alpha's, gamma's are non_negative
lb = [zeros(1,5), repmat(-inf,1,4), zeros(1,5), repmat(-inf,1,5)]; %lower bound
options=optimset('Tolfun',1.0e-10,'MaxIter',1.0e5,'MaxFunEvals',1.0e6);

% minimize negative of log likelihood
[g_est,fval,exitflag,output,lambda,grad,hessian]= fmincon('ordered_probit_like',...
    g0,[],[],[],[],lb,[],[],options,...
    eld,ffrac,landv,lnhdd,ngrw,octy,opop,pgrw,pinc,tpop,tire);

%compare results with paper
gknot = [.86;.03;.15;0;.08;-.49;-.03;.004;-.02;...
    .53;.76;.46;.6;.12;-.74;-.53;2.25;.34;.23]; %paper
[gknot g_est]

%% Step 1b
% compute se using Hessian (use "hessian" from fmincon)
se=sqrt(diag(inv(hessian))); 
% Alternative: use finite differences method (does not work well, not sure
% why)
H = hessian_fun(g_est, eld,ffrac,landv,lnhdd,ngrw,octy,opop,pgrw,pinc,tpop,tire);
se2=sqrt(diag(inv(H)));

%% Step 2
% Point estimates & figure
alpha = g_est(1:5);%5
beta = g_est(6:9);%4
gamma = g_est(10:15);%6
lambda = g_est(16:19);%4
    
for k=1:5
    s(k) = (gamma(6)*mean(landv)+sum(gamma(1:k)))...
    /(2*alpha(1)+mean([eld, pinc, lnhdd, ffrac])*beta-sum(alpha(1:k)))/k;
end

x = [1:5];
y = s(5)./s;
scatter(x,y,'FilledSquares')
xlim([0,6])
xlabel('Number of Firms')
ylabel('S5/SN')
legend('Tire Dealers')

%% Step 3
% Discuss and summarize B&R’s findings:
% The objective of B&R’s paper is to study how market size affects entry,
% and how competitive conduct changes as the number of incumbents in a
% market increases. The authors develope a scale free measure “entry
% threshold ratio,” so that even without prices, costs, or quantity data,
% one can still estimate competitive consequences of entry if she knows the
% number of incumbents in a market. Using entry threshold ratio, they find
% that within a market of five or fewer incumbents, competitive conduct
% increases drastically with the entry of the second and third firm, but
% after that, the market stays at a relatively stable but high competitive
% level.
% 
% Do you find them convincing?
% Their findings make intuitive sense to me.
% If we look at some oligopoly competition models, such as Stackelberg,
% Cournot, and Bertrand, although results depend on specifications of the
% models, we can see that in general, level of competition increase at a
% decreasing rate with more firms in the market. Also, with an increase
% number of incumbents, forming cartel becomes more difficult.
% 
% What do you think of Table 4 and Table 10 in conjunction? 
% In general, if we use the estimated coefficients from Table 4 to compute
% the entry threshold ratio s5/sN, this ratio falls drastically when N
% changes from 1 to 2, and from 2 to 3, but stays almost the same from 3
% on. This should suggest that prices of tires fall significantly when N
% changes from 1 to 2 then to 3, but stays the same after 3. Table 10,
% however, does not show a clear pattern of price decline (both mean and
% median). Plus, Table 4 is based on the assumption that within each
% industry, the products are similar, but from Table 10, the reported
% quality difference is quite large. Therefore, we know that there must
% have  been some other factors that affect prices besides number of
% incumbents, such as wage level, mileage, brand, etc. A problem in Table 4
% is that most of the coefficients are not significant, so using them to
% estimate entry threshold ratio could be a problem.
% 
% Comments:
% I agree that B&R’s paper is a very important and interesting study of the
% relationship between concentration, market size and competition. Their
% construction of the entry threshold ratio is widely used in future IO
% empirical studies.
% 
% One of the advantage of B&R’s framework is that it is very easy to apply.
% Parameters of their model can be estimated with data that are easier to
% get than prices and costs. With all parameters estimated, it is very easy
% to draw conclusion about what kind of competition and profit a potential
% entrant faces. The simplicity of this framework also allows future
% scholars to build on it to study different aspects of concentrated
% market, such as the role of sunk cost and local regulations. Of course
% this simplicity is at the cost of generality. This model is built on many
% assumptions, such as similar product, production technology and costs,
% and no price discrimination in each industry. But in their paper, since
% sample data are carefully preselected to avoid violation of some of these
% assumptions, the results are relatively reliable.
% 
% One of the limits of applying their framework is that their model only
% gives strong results when markets are relatively isolated. In order to
% apply their framework to towns closer to each other, or towns close to
% large cities, it would require collection of a large amount of new data.
% Also, their results might not apply to an industry with differentiated
% products, such as cars. In addition, since car is an expensive
% and durable good for consumers, it makes sense for some of them to drive
% a long distance (way more than 20 miles) to get a car they like or a
% better deal. Therefore, for car dealerships, 20 miles is not enough to form
% an isolated market.



